type = "card"
title = "Honors and Awards"
# description = "Honors and awards I have received."

[[items]]
title = "Top Ten Students of the Year"
subtitle = "NERCVT, Peking University"
date = "2025"

[[items]]
title = "Merit Student"
subtitle = "Peking University"
date = "2025"

[[items]]
title = "National Scholarship"
date = "2019,2020,2021"

[[items]]
title = "Outstanding Student Model"
subtitle = "Northwestern Polytechnical University"
date = "2020"

[[items]]
title = "National Champion of China Robotics Competition"
subtitle = "Basketball Robot"
date = "2020"

[[items]]
title = "National First Prize of RoboMaster Competition"
date = "2020"


# [[items]]
# title = "Example Award"
# subtitle = "Organization"
# date = "2024"
# content = "Description of the award."

# [[items]]
# title = "Example Award"
# subtitle = "Organization"
# date = "2023"
# content = "Description of the award."

# [[items]]
# title = "Example Award"
# subtitle = "Organization"
# date = "2022"
# content = "Description of the award."
