
[[items]]
title = "Peking University, Ph.D. in School of Computer Science"
subtitle = "Supervised by Prof. Shiliang Zhang"
date = "2022 - Present"

[[items]]
title = "Northwestern Polytechnical University, BSc in School of Software"
subtitle = "Outstanding Graduate of Shaanxi Province, Practice Research Advised by Prof. Peng Wang"
date = "2018 - 2022"
