type = "card"
title = "Education"

[[items]]
title = "Peking University"
subtitle = "Ph.D. in School of Computer Science, Supervised by Prof. Shiliang Zhang"
date = "2022 - Present"

[[items]]
title = "Northwestern Polytechnical University"
subtitle = " BSc in School of Software. Practice Research Advised by Prof. Peng Wang"
date = "2018 - 2022"
