[[news]]
date = "2025-09"
content = "ðŸŽ‰ MagCache about fast video generation has been accepted by NeurIPS 2025"

[[news]]
date = "2025-05"
content = "ðŸŽ‰ EMLoC about long-context learning has been accepted by ICML 2025"

[[news]]
date = "2025-02"
content = "ðŸŽ‰ MMRef about multi-modal representation learning has been accepted by IEEE TMM"

[[news]]
date = "2024-03"
content = "ðŸŽ‰ OVMR about open-vocabulary recognition has been accepted by CVPR 2024"